highlighting: pygments
permalink: "/:year/:month/:title"
title: The JRuby Blog
subtitle: The Ruby Programming Language on the JVM
url: http://blog.jruby.org
markdown: kramdown
kramdown:
  input: GFM
plugins:
- jekyll-asciidoc
asciidoctor:
  attributes:
    icons: font
    source-highlighter: pygments
    pygments-css: style
